const food = [
    {
        name: "Raspberry Eclair",
        img: "https://th.bing.com/th/id/R.59fead8b87c6641be4e4c73145244da5?rik=Zayssi3li%2fmwBw&pid=ImgRaw&r=0",
        price: "$4.50",
        seasonal: "no",
        bev: false,
    },

    {
        name: "Pain au Chocolat",
        img: "https://gateaux-et-delices.com/wp-content/uploads/2016/02/Pains-au-chocolat-express1-1.jpg",
        price: "$4",
        seasonal: "no",
        bev: false,
    },

    {
        name: "Tiramisu",
        img: "https://preppykitchen.com/wp-content/uploads/2018/06/Tiramisu-Blog-a.jpg",
        price: "$5",
        seasonal: "no",
        bev: false,
    },
    {
        name: "Pumpkin Pie Cheesecake Slice",
        img: "https://iwashyoudry.com/wp-content/uploads/2021/09/Pumpkin-cheesecake-slice-plate-feature-500x500.jpg",
        price: "$5.50",
        seasonal: "Fall",
        bev: false,
    },
    {
        name: "White Chocolate Peppermint Cookies",
        img: "https://celebratingsweets.com/wp-content/uploads/2021/12/Peppermint-Cookies-6.jpg",
        price: "$4.50",
        seasonal: "Christmas",
        bev: false,
    },
    {
        name: "Peppermint Mocha Latte",
        img: "https://bakingmischief.com/wp-content/uploads/2018/12/peppermint-mocha-image-square-1-400x400.jpg",
        price: "$3.50",
        seasonal: "Christmas",
        bev: true,
    },
    {
        name: "Red Velvet Battenberg Cake Slice",
        img: "https://bakefromscratch.com/wp-content/uploads/2015/11/Bobs-Battenberg947JBweb-696x557.jpg",
        price: "$6",
        seasonal: true,
        bev: false,
    },
    {
        name: "Hot Chocolate",
        img: "https://proposal007.com/wp-content/uploads/2020/11/AdobeStock_234224425-1.jpeg",
        price: "$2",
        seasonal: "Fall",
        bev: true,
    },
    {
        name: "Apple Pie Slice",
        img: "https://dinnerthendessert.com/wp-content/uploads/2019/09/Apple-Pie-2-1360x889.jpg",
        price: "$3.50",
        seasonal: "Fall",
        bev: false,
    },
    {
        name: "Gingerbread Man",
        img: "https://img.bestrecipes.com.au/YiZl9KML/w643-h428-cfill-q90/br/2017/11/christmas-gingerbread-men-recipe-521819-1.jpg",
        price: "$2.50",
        seasonal: "Christmas",
        bev: false,
    },
    {
        name: "Croissant",
        img: "https://uploads.lebonbon.fr/source/2019/may/h9t1i0ja6b_2_1600.jpg",
        price: "$3",
        seasonal: "no",
        bev: false,
    },
    {
        name: "Blackberry Tart",
        img: "https://lh3.googleusercontent.com/-V3e2-QwrO_4/TW6XLON0edI/AAAAAAAAAlA/6NN5c11VgvQ/s1600/IMG_1519.JPG",
        price: "$2.50",
        seasonal: "Fall",
        bev: false,
    },
    {
        name: "Apple Fritter",
        img: "http://www.cindysrecipesandwritings.com/wp-content/uploads/2018/09/Apple-Fritter.jpg",
        price: "$3",
        seasonal: "Fall",
        bev: false,
    },
    {
        name: "Chocolate Candy Cane Cake Slice",
        img: "https://www.thespruceeats.com/thmb/D6K-hZ52vN05ZsL1bFor32fuLXI=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/ChocolateCandyCaneCake-ElizabethLaBau-5b6b68bf46e0fb00509a20e5.jpg",
        price: "$4.50",
        seasonal: "Christmas",
        bev: false,
    },
    {
        name: "Eggnog",
        img: "https://bigoven-res.cloudinary.com/image/upload/t_recipe-1280/simple-eggnog.jpg",
        price: "$2",
        seasonal: "Christmas",
        bev: true,
    },
];

export { food };